const data = [
	{
		title: "Expanding Cards",
		day: 1,
		img_link: "./_images/expanding_cards_sc.png",
		project_link: "./Expanding Cards/index.html",
	},
	{
		title: "Progress Steps",
		day: 2,
		img_link: "./_images/progress_steps_sc.png",
		project_link: "./Progress Steps/index.html",
	},
	{
		title: "Rotating Navigation",
		day: 3,
		img_link: "./_images/rotating_navigation_sc.png",
		project_link: "./Rotating Navigation/index.html",
	},
	{
		title: "Hidden Search Widget",
		day: 4,
		img_link: "./_images/hidden_search_widget_sc.png",
		project_link: "./Hidden Search Widget/index.html",
	},
	{
		title: "Blurry Loading",
		day: 5,
		img_link: "./_images/blurry_loading_sc.png",
		project_link: "./Blurry Loading/index.html",
	},
	{
		title: "Scroll Animation",
		day: 6,
		img_link: "./_images/scroll_animation_sc.jpg",
		project_link: "./Scroll Animation/index.html",
	},
	{
		title: "Split Landing Page",
		day: 7,
		img_link: "./_images/split_landing_page_sc.png",
		project_link: "./Split Landing Page/index.html",
	},
	{
		title: "Form Wave Animation",
		day: 8,
		img_link: "./_images/form_wave_animation_sc.png",
		project_link: "./Form Wave Animation/index.html",
	},
	{
		title: "Sound Board",
		day: 9,
		img_link: "./_images/sound_board_sc.png",
		project_link: "./Sound Board/index.html",
	},
	{
		title: "Dad Jokes",
		day: 10,
		img_link: "./_images/dad_jokes_sc.png",
		project_link: "./Dad Jokes/index.html",
	},
	{
		title: "Event Keycodes",
		day: 11,
		img_link: "./_images/event_keycodes_sc.png",
		project_link: "./Event Keycodes/index.html",
	},
	{
		title: "FAQ Collapse",
		day: 12,
		img_link: "./_images/faq_collapse_sc.png",
		project_link: "./FAQ Collapse/index.html",
	},
	{
		title: "Random Choice Picker",
		day: 13,
		img_link: "./_images/random_choice_picker_sc.png",
		project_link: "./Random Choice Picker/index.html",
	},
	{
		title: "Animated Navigation",
		day: 14,
		img_link: "./_images/animated_navigation_sc.png",
		project_link: "./Animated Navigation/index.html",
	},
	{
		title: "Incrementing Counter",
		day: 15,
		img_link: "./_images/incrementing_counter_sc.png",
		project_link: "./Incrementing Counter/index.html",
	},
	{
		title: "Drink Water",
		day: 16,
		img_link: "./_images/drink_water_sc.png",
		project_link: "./Drink Water/index.html",
	},
	{
		title: "Movie App",
		day: 17,
		img_link: "./_images/movie_app_sc.png",
		project_link: "./Movie App/index.html",
	},
	{
		title: "Background Slider",
		day: 18,
		img_link: "./_images/background_slider_sc.png",
		project_link: "./Background Slider/index.html",
	},
	{
		title: "Theme Clock",
		day: 19,
		img_link: "./_images/theme_clock_sc.png",
		project_link: "./Theme Clock/index.html",
	},
	{
		title: "Button Ripple Effect",
		day: 20,
		img_link: "./_images/button_ripple_effect_sc.png",
		project_link: "./Button Ripple Effect/index.html",
	},
	{
		title: "Drag N Drop",
		day: 21,
		img_link: "./_images/drag_n_drop_sc.png",
		project_link: "./Drag N Drop/index.html",
	},
	{
		title: "Drawing App",
		day: 22,
		img_link: "./_images/drawing_app_sc.png",
		project_link: "./Drawing App/index.html",
	},
	{
		title: "Kinetic CSS Loader",
		day: 23,
		img_link: "./_images/kinetic_css_loader_sc.png",
		project_link: "./Kinetic CSS Loader/index.html",
	},
	{
		title: "Content Placeholder",
		day: 24,
		img_link: "./_images/content_placeholder_sc.png",
		project_link: "./Content Placeholder/index.html",
	},
	{
		title: "Sticky Navbar",
		day: 25,
		img_link: "./_images/sticky_navbar_sc.png",
		project_link: "./Sticky Navbar/index.html",
	},
	{
		title: "Double Vertical Slider",
		day: 26,
		img_link: "./_images/double_vertical_slider_sc.png",
		project_link: "./Double Vertical Slider/index.html",
	},
	{
		title: "Toast Notification",
		day: 27,
		img_link: "./_images/toast_notification_sc.png",
		project_link: "./Toast Notification/index.html",
	},
	{
		title: "Github Profiles",
		day: 28,
		img_link: "./_images/github_profiles_sc.png",
		project_link: "./Github Profiles/index.html",
	},
	{
		title: "Double Heart Click",
		day: 29,
		img_link: "./_images/double_heart_click_sc.png",
		project_link: "./Double Heart Click/index.html",
	},
	{
		title: "Auto Text Effect",
		day: 30,
		img_link: "./_images/auto_text_effect_sc.png",
		project_link: "./Auto Text Effect/index.html",
	},
	{
		title: "Password Generator",
		day: 31,
		img_link: "./_images/password_generator_sc.png",
		project_link: "./Password Generator/index.html",
	},
	{
		title: "Good Cheap Fast Checkboxes",
		day: 32,
		img_link: "./_images/good_cheap_fast_checkboxes_sc.png",
		project_link: "./Good Cheap Fast Checkboxes/index.html",
	},
	{
		title: "Notes App",
		day: 33,
		img_link: "./_images/notes_app.png",
		project_link: "./Notes App/index.html",
	},
	{
		title: "Animated Countdown",
		day: 34,
		img_link: "./_images/animated_countdown.png",
		project_link: "./Animated Countdown/index.html",
	},
	{
		title: "Image Carousel",
		day: 35,
		img_link: "./_images/image_carousel.png",
		project_link: "./Image Carousel/index.html",
	},
	{
		title: "Hoverboard",
		day: 36,
		img_link: "./_images/hoverboard.png",
		project_link: "./Hoverboard/index.html",
	},
	{
		title: "Pokedex",
		day: 37,
		img_link: "./_images/pokedex.png",
		project_link: "./Pokedex/index.html",
	},
	{
		title: "Mobile Tab Navigation",
		day: 38,
		img_link: "./_images/mobile_tab_navigation.png",
		project_link: "./Mobile Tab Navigation/index.html",
	},
	{
		title: "Password Strength Background",
		day: 39,
		img_link: "./_images/password_strength_background.png",
		project_link: "./Password Strength Background/index.html",
	},
	{
		title: "3D Background Boxes",
		day: 40,
		img_link: "./_images/3D_background_boxes.png",
		project_link: "./3D Background Boxes/index.html",
	},
	{
		title: "Verify Account UI",
		day: 41,
		img_link: "./_images/verify_account_ui.png",
		project_link: "./Verify Account UI/index.html",
	},
	{
		title: "Live User Filter",
		day: 42,
		img_link: "./_images/live_user_filter.png",
		project_link: "./Live User Filter/index.html",
	},
	{
		title: "Feedback UI Design",
		day: 43,
		img_link: "./_images/feedback_ui_design.png",
		project_link: "./Feedback UI Design/index.html",
	},
	{
		title: "Custom Range Slider",
		day: 44,
		img_link: "./_images/custom_range_slider.png",
		project_link: "./Custom Range Slider/index.html",
	},
	{
		title: "Netflix Navigation",
		day: 45,
		img_link: "./_images/netflix_navigation.png",
		project_link: "./Netflix Navigation/index.html",
	},
	{
		title: "Quiz App",
		day: 46,
		img_link: "./_images/quiz_app.png",
		project_link: "./Quiz App/index.html",
	},
];

export default data;
